### ISSUE TITLE
Мутируется проп методом sort

### ISSUE THREAD

**Issue by splincool** [Angloya/dota-random-hero#1]
https://github.com/Angloya/dota-random-hero/blob/ae76ff6a151436de2216640c7d9397d648acf2e2/src/components/HeroesGroup.tsx#L11

В этом месте применяя метод `sort()` к `heroes` происходит мутация пропса `heroes`, что не очень хорошо.
Предлагаю либо делать копию heroes и уже копию сортировать, либо попробовать использовать новый метод `toSorted()`

**Comment by Angloya** [comment]
Поправила, поменять на toSorted() не получилось так как в node еще не очень обширная поддержка только от 20 версии ноды, поэтому сделала копию
